services:
  crossgame-db:
    image: postgres:17.5-alpine3.21
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: 'America/Santiago'
      PGTZ: 'America/Santiago'
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: crossgame-db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  principal_app:
    build: .
    ports:
      - "4000:80"
      - "4010:8080"
    environment:
      PORT: 80
      WS_PORT: 8080
      ENVIRONMENT: ${ENVIRONMENT}
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      VALIDATION_GAME_KEYS: ${VALIDATION_GAME_KEYS}
    depends_on:
      - crossgame-db
    links:
      - crossgame-db